@config = {"EVENT_NAME":"201905_LeBeigesHydra","EVENT_EXPIRED":"2019/05/12 23:59:59","DE_REDEMPTION_DEV":"00_SamplingTest_Redemption_TWN_FBP","DE_REDEMPTION_PRO":"00_SamplingMaster_Redemption_TWN_FBP","SMS_ARR":["00_TestList_MDM_SMS_TWN_FBP","20190403_LeBlancSC01SCUV_SMS_TWN_FBP","20190403_LeBlancSC02MU_SMS_TWN_FBP","20190403_LeBlancSC03Face_SMS_TWN_FBP","20190403_LeBlancSC04HB_SMS_TWN_FBP"]}
@key = 08d366a4-592e-4dd5-a51d-ae8636a79f11

# 店家列表
GET https://cloud.e-news.chanel.com/common_boutique_list_tw HTTP/1.1


### Encrypt
POST https://cloud.e-news.chanel.com/admin_api_encrypt HTTP/1.1
Content-Type: application/x-www-form-urlencoded

key={{key}}
&config={{config}}