name: deploy gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
      PUBLISH_BRANCH: gh-pages
      PUBLISH_DIR: ./dist 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        git config --global user.email milkmidi@gmail.com
        git config --global user.name milkmidi
        cd dist
        git rm -rf .git
        git init
        git add .
        git commit -a -m "deploy to Github pages"
        git push --force ${{secrets.commit_secret}}@github.com:milkmidi/The-F2E---Rapid-Chat.git master:gh-pages
        echo complete.
